server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: financial-reports-v1
          uri: lb://financial-reporting-service-v1
          predicates:
            - Path=/api/v1/financial-reports/**
          filters:
            - AddRequestHeader=X-API-Version,v1

        - id: financial-reports-v2
          uri: lb://financial-reporting-service-v2
          predicates:
            - Path=/api/v2/financial-reports/**
          filters:
            - AddRequestHeader=X-API-Version,v2

  datasource:
    url: jdbc:mysql://localhost:3306/financial_reports
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
