package com.system.ids;

import java.time.LocalDateTime;

/**
 * Represents an alert generated by the IDS.
 */
public class Alert {
    private String id;
    private String message;
    private LocalDateTime timestamp;

    // Constructor
    public Alert(String id, String message, LocalDateTime timestamp) {
        this.id = id;
        this.message = message;
        this.timestamp = timestamp;
    }

    // Getters and Setters
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public LocalDateTime getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(LocalDateTime timestamp) {
        this.timestamp = timestamp;
    }
}
