# config/catalog_index.yaml
catalog_index:
    title: 'The DIY Store - Catalog'
    top: 'The DIY Store - Catalog'
    top2: 'Select one of the following categories'
    bottom: 'If you have any questions or problems, please contact admin@baumarkt.de'
