pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'docker run --rm -v $(pwd):/app -w /app arm32v7/debian:latest /bin/bash -c "apt-get update && apt-get install -y g++ make && g++ -std=c++11 -pthread main.cpp rtos.cpp -o rtos"'
            }
        }
    }
}
