version: '3.8'

services:
  market_maker:
    build: .
    container_name: crypto_market_maker
    ports:
      - "8080:8080" # Adjust as needed for your application
    volumes:
      - .:/app
    environment:
      - ENV=production  # Change based on the environment
    restart: always
