# Configuration for the Model Serving Service

# Model configuration
model:
  path: "trained_models/titanic_model.pkl"  # Path to the trained model file
  input_features:                             # List of expected input features
    - Pclass
    - Sex
    - Age
    - SibSp
    - Parch
    - Fare
    - Embarked

# Logging configuration
logging:
  level: INFO                               # Logging level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
  format: "%(asctime)s - %(levelname)s - %(message)s"  # Log message format
  file: "logs/model_serving.log"           # Path to the log file

# Server configuration
server:
  host: "0.0.0.0"                           # Host where the server will run
  port: 5000                                 # Port on which the server will listen

# Other configurations can be added as needed
