# config/shipping_info.yaml
shipping_info:
    title: 'The DIY store: Shipping data'
    top: 'Place an order: Shipping data'
    top2: 'If you have any questions or problems, please contact admin@baumarkt.de'
    bottom: 'If you have any questions or problems, please contact admin@baumarkt.de'
    fields:
        email: 'E-Mail Address'
        vers_name: 'First-/Lastname'
        vers_strasse: 'Street'
        vers_ort: 'City'
        sta: 'State'
        vers_postl: 'Zip code'
        telefon: 'Phone'
        cc_type: 'Credit card type'
        cc_number: 'Credit card number'
        cc_exp: 'Valid until'
    cc_types:
        visa: 'Visa'
        mc: 'Mastercard'
        amex: 'American Express'
    length:
        email: '55'
        vers_name: '40'
        vers_strasse: '55'
        vers_ort: '40'
        vers_postl: '10'
        telefon: '15'
        cc_number: '20'
    months:
        1: 'January'
        2: 'February'
        3: 'March'
        4: 'April'
        5: 'May'
        6: 'June'
        7: 'July'
        8: 'August'
        9: 'September'
        10: 'October'
        11: 'November'
        12: 'December'
