<?php
/*
 * file: fields_product_page.inc
 * reason: Defines the variables and creates the variables to be displayed
 *        the product page of the catalog required Arrays
 */
$page = array(
    "title" => "The DIY Store - Catalog",
    "top" => "The DIY Store - Catalog",
    "bottom" => "If you have any questions or problems, please contact admin@baumarkt.de"
);
$table_heads = array(
    "katalog_nr" => "Art.Nr.",
    "name" => "Name",
    "pr_beschr" => "Description",
    "preis" => "Price",
    "menge" => "Quantity"
);
?>