<?php
/*
 * file: fields_cart-oo.inc
 * reason: Contains the information required to display the shopping cart relevant data
 */
$page = array(
    "title" => "The DIY Store - SHopping cart",
    "top" => "The DIY Store",
    "top2" => "Shopping Cart",
    "bottom" => "If you have any questions or problems, please contact admin@baumarkt.de"
);
$table_headers = array(
    "Pos.","Kat.Nr.","Bezeichnung","Menge",
    "Preis","Gesamt"
);
?>